config:
  credentials: []
  project_repos:
    github.com/AtefBN/esgpullUtilties:
      branch: main
      repo: https://github.com/AtefBN/esgpullUtilties
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/AtefBN/esgpullUtilties git:
        commands:
        - /usr/bin/env sh .sqa/script.sunny-chartreuse-goat.sh
        container: qc.acc_pasty-grey-bison
  QC.Doc:
    repos:
      github.com/AtefBN/esgpullUtilties find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.freaky-smalt-angora.sh
        container: qc.doc_blurry-lavender-warthog
      github.com/AtefBN/esgpullUtilties git:
        commands:
        - /usr/bin/env sh .sqa/script.lumpy-gold-shark.sh
        container: qc.doc_paltry-apricot-oyster
      github.com/AtefBN/esgpullUtilties markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.wheezy-cornflower-turkey.sh
        container: qc.doc_skimpy-seashell-zebra
  QC.Lic:
    repos:
      github.com/AtefBN/esgpullUtilties licensee:
        commands:
        - /usr/bin/env sh .sqa/script.stuffy-emerald-abyssinian.sh
        container: qc.lic_wimpy-razzmatazz-lemming
  QC.Sec:
    repos:
      github.com/AtefBN/esgpullUtilties bandit:
        commands:
        - /usr/bin/env sh .sqa/script.sleazy-pumpkin-cockroach.sh
        container: qc.sec_slimy-ruby-chicken
  QC.Sty:
    repos:
      github.com/AtefBN/esgpullUtilties flake8:
        commands:
        - /usr/bin/env sh .sqa/script.wiggy-cinnabar-gerbil.sh
        container: qc.sty_slimy-brown-cat
  QC.Uni:
    repos:
      github.com/AtefBN/esgpullUtilties pytest:
        commands:
        - /usr/bin/env sh .sqa/script.skimpy-white-mayfly.sh
        container: qc.uni_leaky-goldenrod-mongrel
  QC.Ver:
    repos:
      github.com/AtefBN/esgpullUtilties get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.jumpy-ultramarine-fish.sh
        container: qc.ver_flabby-sepia-spaniel
timeout: 5400
